{
  "comments": [
    {
      "key": {
        "uuid": "4dbaee15_6119fc24",
        "filename": "src/system/kernel/vm/vm.cpp",
        "patchSetId": 2
      },
      "lineNbr": 6587,
      "author": {
        "id": 1000011
      },
      "writtenOn": "2021-07-24T00:56:26Z",
      "side": 0,
      "message": "I wonder why we return two different error codes here instead of just one? A holdover from BeOS perhaps?",
      "revId": "31acddc00e77a0da9257bf70f6f89e7ccce91b1a",
      "serverId": "40b9299a-d8a8-485d-9b01-e6d3f45eefb5",
      "unresolved": true
    }
  ]
}