{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "2d0c255a_be23e0f0",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1000023
      },
      "writtenOn": "2022-11-09T15:49:48Z",
      "side": 1,
      "message": "fssh:/\u003e write_vnode_entry called on invalid cluster (1)\ndosfs_create: failed to update directory last-modified time when creating a new file in (null) (Invalid argument)\nfssh:/\u003e ",
      "revId": "a0105cb94fd55c8c01b3ba87fa8fb4b258c2e8e8",
      "serverId": "40b9299a-d8a8-485d-9b01-e6d3f45eefb5"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "059de5d6_dcea7088",
        "filename": "src/add-ons/kernel/file_systems/fat/file.cpp",
        "patchSetId": 4
      },
      "lineNbr": 465,
      "author": {
        "id": 1000023
      },
      "writtenOn": "2022-11-09T17:11:42Z",
      "side": 1,
      "message": "it\u0027s better to ignore failure here, as it seems write_vnode_entry return status is ignored...",
      "revId": "a0105cb94fd55c8c01b3ba87fa8fb4b258c2e8e8",
      "serverId": "40b9299a-d8a8-485d-9b01-e6d3f45eefb5"
    }
  ]
}